services:
  model_backend:
    build: 
      context: ./backend  # <-- Points to our new custom Dockerfile
    ports:
      - "5080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      model_backend:
        condition: service_healthy