import sys
from io import StringIO
import boto3
import pandas as pd

from src.logger import logger
from src.exception import CustomException

class S3Operations:
    """
    A utility class to interact with AWS S3, providing methods to fetch files from a bucket.
    """
    
    def __init__(self, bucket_name: str, aws_access_key: str, aws_secret_key: str, region_name: str = 'us-east-1'):
        """
        Initializes the S3 client and binds context to the logger.
        
        Args:
            bucket_name (str): The name of the target AWS S3 bucket.
            aws_access_key (str): AWS access key ID.
            aws_secret_key (str): AWS secret access key.
            region_name (str): AWS region. Defaults to 'us-east-1'.
            
        Raises:
            CustomException: If the connection to AWS fails.
        """
        self.bucket_name = bucket_name
        
        # Bind the service name and bucket to all logs generated by this instance
        self.log = logger.bind(service='S3Storage', bucket=self.bucket_name)

        try:
            self.s3_client = boto3.client(
                's3',
                aws_access_key_id=aws_access_key,
                aws_secret_access_key=aws_secret_key,
                region_name=region_name
            )
            self.log.info("Successfully initialized S3 client")

        except Exception as e:
            self.log.error('S3 client initialization failed', error=str(e))
            raise CustomException(e, sys)
        

    def fetch_file_from_s3(self, s3_key: str) -> pd.DataFrame:
        """
        Fetches a CSV file object matching a specific key from S3 and loads it into a DataFrame.

        Args:
            s3_key (str): The exact filename or path/key in the S3 bucket.

        Returns:
            pd.DataFrame: A DataFrame containing the parsed contents of the CSV file.
            
        Raises:
            CustomException: If the file cannot be fetched or parsed.
        """
        try:
            self.log.info('Attempting to fetch file from S3', s3_key=s3_key)
            
            obj = self.s3_client.get_object(Bucket=self.bucket_name, Key=s3_key)
            csv_content = obj['Body'].read().decode('utf-8')
            df = pd.read_csv(StringIO(csv_content))
            
            self.log.info('File fetched and parsed successfully', s3_key=s3_key, row_count=len(df))
            return df
        
        except Exception as e:
            self.log.error('Failed to fetch file from S3', s3_key=s3_key, error=str(e))
            raise CustomException(e, sys)