import os
import sys
import json
import dagshub
import mlflow
from mlflow.tracking import MlflowClient
from dotenv import load_dotenv

from src.logger import logger
from src.exception import MyException
from src.utils.helper_functions import load_params

load_dotenv()
# Initialize DagsHub exactly as you did in evaluation
dagshub.init(repo_owner='Nirmal-Yadagani', repo_name='movie-review-sentiment-analysis', mlflow=True)

def get_current_Staging_metric(client, model_name, metric_name):
    """Fetches the specified metric for the current Staging model."""
    try:
        stage_model = client.get_model_version_by_alias(name=model_name, alias="Staging")
        stage_run = client.get_run(stage_model.run_id)
        stage_metric = stage_run.data.metrics.get(metric_name)
        return stage_metric, stage_model.version
    except Exception as e:
        logger.info(f"No existing Staging model found for {model_name}. Proceeding as first deployment.")
        return None, None

def promote_model():
    try:
        logger.info("Loading promotion parameters and artifacts...")
        params = load_params('params.yaml')
        
        # Pulling configurations from your params.yaml
        eval_params = params['model_evaluation']
        promo_params = params.get('model_promotion', {})
        
        target_metric = promo_params.get('target_metric', 'f1_score')
        improvement_threshold = promo_params.get('improvement_threshold', 0.01) # e.g., 1% improvement
        register_model_name = eval_params['register_model_name']
        
        # Load the artifacts generated by model_evaluation.py
        with open(eval_params['metrics_file_path'], 'r') as f:
            new_metrics = json.load(f)
        
        with open(eval_params['model_info_file_path'], 'r') as f:
            model_info = json.load(f)

        new_metric_value = new_metrics.get(target_metric)
        new_run_id = model_info.get('run_id')
        
        if new_metric_value is None:
            raise MyException(f"Metric {target_metric} not found in evaluated metrics.", sys)

        client = MlflowClient()
        
        # 1. Get the newly registered model version using the run_id
        versions = client.search_model_versions(f"name='{register_model_name}'")
        new_model_version = next((v.version for v in versions if v.run_id == new_run_id), None)
        
        if not new_model_version:
             raise MyException("Could not find the registered model version for the current run.", sys)

        # 2. Compare against Staging
        logger.info(f"Comparing new model (Run: {new_run_id}) against Staging.")
        stage_metric_value, stage_version = get_current_Staging_metric(client, register_model_name, target_metric)

        promote = False

        if stage_metric_value is None:
            logger.info("First model detected. Promoting directly to Staging.")
            promote = True
        else:
            # Calculate improvement (assuming higher is better for F1/Accuracy)
            improvement = new_metric_value - stage_metric_value
            logger.info(f"Staging {target_metric}: {stage_metric_value:.4f}")
            logger.info(f"New Model {target_metric}: {new_metric_value:.4f}")
            logger.info(f"Improvement: {improvement:.4f} (Threshold: {improvement_threshold})")

            if improvement >= improvement_threshold:
                logger.info("Model passed the improvement threshold.")
                promote = True
            else:
                logger.info("Model did not meet the improvement threshold. Skipping promotion.")

        # 3. Apply the alias
        if promote:
            client.set_registered_model_alias(
                name=register_model_name, 
                alias="Staging",
                version=new_model_version
            )
            logger.info(f"Successfully promoted version {new_model_version} of {register_model_name} to Staging.")

    except Exception as e:
        if isinstance(e, MyException):
            raise e
        raise MyException(e, sys)

if __name__ == "__main__":
    promote_model()